sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product sqr-035
env:
  global:
    -
      # LTD_AWS_ID
      secure: IC2p0mWbpE5ucmThqsua+HLhIPgAZLyR0JBkSdgBgXRDkLhhSsCFzcH9g8AhYQV6KmPJJsvKp6bGoRoDnvxEsmaB2CrdwtckfDVLx1m+A+FGjxXp+INENq4UZ/CPYSSQefpbECxHWZiHiYjJM0Y9v93fxRyPJh/tYYIgVoV0urYCKdyxOPFWBxFTq09A1cPQZzyhWuKU+8UKbT0/uEJKIcwFD9t+6kidk0QbIkC8A80YMIpo51RiLg8AUZ+sxyDM0cZHUfTi6TQYJB3wse8Bl2JjvcmHBllNzPkrUbkMNcYijL3On+M68rHW+3cmMXunDpyZgtccCZ/nqmC90BKT+4LDx/uIzaxIUgsTi3UJt6lvazuAdI9h7JykTtjhuaW0Oev7BOAiBzCRcg2iQUNiQhUvphnHos79mAFytWBBl0hEBOCFDJBREy6fr8HKvqVh9xRxgmoNxlbzufAssLwEMN0k6toSTRbWUXUjl/8FsxcYSRLpikWZXgJR96djhnO1bsqnaPHd/OWSulj1Nn1E7mo3Ux7JBZNXB54eadebPHV5by6ouUj8H2l6D0pkPpWdsybKBoCGuEBwfw0qWRWbDFjDqn/81uLNsVKQKZUypRwFlImyVk1oC9yJIxy5yPq9wANv6fHfpAhl1EqgMn+AdE5Lz2U00labeWwGvn7yMrI=
    -
      # LTD_AWS_SECRET
      secure: VnXXkAoiQuKG03ZkfAXokjr5VGagAZk567kEYFw3q7pgqE297ckimCMpyMc4jibuMV8ZBg/Mdc7oMqAPRmquWzOPVCZdnYrM5OePJNjQ/BNLgx6Hh7DGhAzPDiu+hro4sTU3OTkZOueQGbwD7C3/bCqg3B5GEwAEhKzDnEPCMgBUo0Of8XTivBP3kTUAIdPgfr5WOPE2OSPiYH1hGBY0wlhJbiB2EqewNcGvRgrJ5oDzkhgA6JTi0mAlsaj2mHVKRw8i44VdcasWLnbYTtO1bqCwndUgabGVNJ7k/47y/tAL+V5Ene7MwrJQZsqtp0Hwz9yECVAYjeI/g7Do6ECd3FRmIxOtkywuNen0nB9L6LCAiOEyUHUnag4x1JCANbn8A1IYs0JhWu/OyfzxbzE68SfmEdB/78JEzcKiO5CQ8r2zAzvGm3Mj61RyFpGfYsQwD7Kq2eEGNmBOEkXNoBJD65UHn4EcPxmyX7jR8awOiG6hLdIIToTtIHdnCxpgI2Az9JPhTTn+ZQRZ3KqS5D7MnOont2fo0zj7JLwwDxMrc8bCguUDz2LiVbnnQTppHgxYc0IIRLpE2Wcev7sZ7SnbJiP0K1W+8JUo+Ery5jefh2JWeMPtxd5SuC0F/fZBoB5RBKrLGOIEP6RL3GkjTrVCZ2qi6TQ903evlpSmxPnr/HU=
    -
      # LTD_USERNAME
      secure: t1f1eL2EKw8hs0JORioIz5ejnQ7rPuSdmzxnDJzNm7YGRptzhHkONeaORBmHTdHt6tk1wFgYyV8sGlJqmD/IaIXYysgpc7iL2sUve9sJ8dTYuMaZxgvpywfKZLD8F8btnZOzdCVnVOav0nyqJMnwY87FLiPMwgjlBDrF07EdZhOjsTzoC9QiRP42q+5ZtJuVG/FvRP6HVtBWFLB7Ms6aqk4ZD6jS4Jz5AYkPdOtLM7HJavZ/l5ryReS6UImqaGHlHjpA76qpzOfm1wDLoWApgbkRIIWYtu5x3/TYBOzT0JzzI+fkGh81JeJ+PRndRCbr5cJwA+FpVVJmKd9UBP4sssqlQx4Y9coscV8GxR5RHRbzd72OYqLJwSZZBomgOcCMiDWv944IPpHcz+6Efq1P8BSkfizhu59ILq+00OIrZ559uSOnoOdjdFBsRoeXAK+Cy/noFgjdmikJPk65kUdPBfxULkOa0F1yUrlE3EuT3B76oPw3rC5f4w7Pdz7xCZ9JL5qgrABvvMUJ9SFpaFa4qs1SKvXfYs1zjzLZqrwYe11MOuExyEnso+QQfd2uJ3nYVH+ahuFZLQS90AA5uICzd3Sri+uQ+Cv10O3mSPdSZVuphifMwVKtLlrlRYqXZz90KPzlALV14yRywHKdI6ExAzJ9J8gxpxbwLtNJss9/7Dw=
    -
      # LTD_PASSWORD
      secure: IltWCZG/NMkK0pehN9frSDUFPaiG2dwu0zQAdP+yV3O3xh7aiHKs9DbiHuWtLbnd/wn3tzC1c/4vYYrk8yHJLUu7HroaCzwquY9KR1dJ7ICRnwTPKrzApraAngu3mGnR0uhW7NALydOdqZo1E9w0HVNpL4MggxXBdFn9KaO54m4aJXXObidNN9eNmdGnujaXFZNfajE+techZYtqYI/okbOGf6ivzZy58ApJ9pWmqiatYDbGpAQw5p0puq0JGMQA1QGPw3MQhwsziq0qX4dpdjm37LjydquDy74VYlx1aD6XDXl0qbThjVy951TstOXg4nphqwlQRN3HdIkWko/BHfsoK7aEBk6+yeLxJmM1bA2KBZf5w/+jsdDXSXcYaa4KV3jE4NmVHFDUUuwPdcd2PPxMTDcLZa+pTGEtSYauyx0hY+XBlDHRqiE8b3JgBiqKld9Vfv91KMBR/WUTP5W5G3LPBE68PZRVTraYdZb+ajoeU2CQulbUqA4OL2VttxdMRoWTEZrH4wE4xzl9tlzqy9iClZOUZaA+Htgb4Y0JoFttUIfrtIoh490mQq6YUeu1Bz+iSWk1R2QlBhxePJzWVkvBDWU5HqY96CvGifuPptLyN7OSk++S2NTGsRp15qtSBFGXTPsSYjAM1mhIVlyakDfkEzbq1eA0xx1nMKNPbT0=
